### ISSUE TITLE
Issues: Controller status screen saying why it is paused.

### ISSUE THREAD

**Issue by kennethLeeHarris** [muxall/RPTCQ-LCD#89] opened 2020-08-03 16:43 UTC

**Comment by muxall** [comment] 2021-02-10 20:55
I was not able to reproduce this issue in 0.513

**Comment by muxall** [comment] 2021-06-28 13:33
Pause messages:  Ignit Fail and Flame Out.

**Comment by muxall** [comment] 2022-07-06 17:28
Fixed in V0.608

**Closed as completed by muxall** 2022-07-06 17:28 UTC
