### ISSUE TITLE
Issue: Cool Down Time flashes 150 temp.

### ISSUE THREAD

**Issue by kennethLeeHarris** [muxall/RPTCQ-LCD#74] opened 2020-07-02 19:48 UTC
When going from profile 4 to cool down, the temp 150 was flashed for a second.

**Comment by muxall** [comment] 2021-06-28 13:26
Unable to reproduce in 0.515.  May have been fixed with other p0 profile fixes.

**Closed as completed by muxall** 2021-06-28 13:26 UTC
